//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OurLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class book_issue
    {
        public string id { get; set; }
        public string book_record_id { get; set; }
        public string issue_id { get; set; }
        public int qty { get; set; }
        public string ref_issue { get; set; }
    
        public virtual book_record book_record { get; set; }
        public virtual issue issue { get; set; }
    }
}
