//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OurLibrary.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LibraryEntities : DbContext
    {
        private static LibraryEntities libEntities = null;

        public static LibraryEntities Instance()
        {
            if (libEntities == null)
            {
                libEntities = new LibraryEntities();
            }
            return libEntities;
        }

        private LibraryEntities()
            : base("name=LibraryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<author> authors { get; set; }
        public virtual DbSet<book> books { get; set; }
        public virtual DbSet<book_issue> book_issue { get; set; }
        public virtual DbSet<book_record> book_record { get; set; }
        public virtual DbSet<category> categories { get; set; }
        public virtual DbSet<@class> classes { get; set; }
        public virtual DbSet<issue> issues { get; set; }
        public virtual DbSet<publisher> publishers { get; set; }
        public virtual DbSet<student> students { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<visit> visits { get; set; }
    }
}
